/**
@file GamePlayScene.h
@brief Manages the gameplay properties.
*/
#pragma once

#include "Scene.h"

#include <string>

#include "Client.h"
#include "Vector2D.h"

#define INVALID_SYMBOL_GUESS -1	//!< Value used to set a symbol guess as invalid.
#define ATTEMPT_DELAY 4.0f	//!< The delay between each symbol attempt.
#define MAX_NUMBER_OF_PARTICLES	500	//!< The maximum number of particles.

class ParticleManager;

/*! \class GamePlayScene
	\brief Manages the gameplay properties.
*/

class GamePlayScene : public Scene {
private:
	Client m_Client;	//!< A client instance, used to communicate with the server.
	std::string m_PlayerEntityID = "PlayerCard";	//!< The name of the player's card entity.
	std::string m_DeckEntityID = "DeckCard";	//!< The name of the dekc's card entity.
	Vector2Df m_MousePosition;	//!< The mouse position, within the window.
	sf::Int32 m_PlayerSymbolIDGuess = INVALID_SYMBOL_GUESS;	//!< The symbol guessed, by the player.
	sf::Int32 m_RoundsWon = 0;	//!< The number of rounds the player has won.
	float m_Score = 0.0f;	//!< The score the player has accumulated, by winning rounds.
	float m_TimeOfLastAttempt = -ATTEMPT_DELAY;	//!< The last time the player guessed a symbol.
	std::shared_ptr<ParticleManager> m_ParticleManager;	//!< Pointer to a particle manager, which manages the particle system.
	bool m_CouldConnect = true;	//!< Manages the connection state between the server and the client.

	/*!
		\brief Handles incoming packets, from the server.
		\param p_Packet The packet to handle (received from the server).
		\return Nothing.
	*/
	void HandlePacket(sf::Packet &p_Packet);
	/*!
		\brief Creates an entity, from a packet of data with values for the entity's components.
		\param p_EntityName The name of the entity, to create.
		\param p_Packet The packet that contains the entity's data.
		\param p_PositionOffset The offset position of the entity.
		\return Nothing.
	*/
	void CreateCardEntity(const std::string &p_EntityName, sf::Packet &p_Packet, const Vector2Df &p_PositionOffset = Vector2Df(0.0f, 0.0f));

public:
	/*!
		\brief Constructor.
		\param p_ScreenSize The size of the screen. 
		\param p_File The User interface file's relative path.
	*/
	GamePlayScene(const Vector2Df &p_ScreenSize, const std::string &p_File);
	~GamePlayScene();	//!< Destructor.

	/*!
		\brief Handles input events, generated by the player.
		\param p_Event The event generated by the player, to be handled.
		\return Nothing.
	*/
	virtual void HandleInputEvent(sf::Event &p_Event) override;

	/*!
		\brief Updates the game play scene.
		\param the delta time between the current frame and the previous.
		\return Nothing.
	*/
	virtual void Update(float p_DeltaTime) override;
	/*!
		\brief Renders the game play scene.
		\return Nothing.
	*/
	virtual void Render() override;

	/*!
		\brief Gets the player's score.
		\return Returns the player's score.
	*/
	float GetPlayerScore();

	/*!
		\brief Gets the amount of rounds won, by the player.
		\return Returns the number of rounds won, by the player.
	*/
	int GetRoundsWon();
};